### ISSUE TITLE
Problems with setup

### ISSUE THREAD

**Issue by josefsabl** [Arachne/EntityLoader#4]
Hey, I have problems setting this stuff up.

Your default installation instructions fail because the class `Contributte\Events\Bridges\Application\DI\EventApplicationBridgeExtension` does not exist.

Okay, I found out that this bridge can be found in `contributte/event-application-bridge` package, and you don't have it in required. So I require it manually. Now I get `Argument 1 passed to Arachne\EntityLoader\Application\FilterRequestParametersSubscriber::requestHandler() must be an instance of Contributte\Events\Extra\Event\Application\RequestEvent, instance of Contributte\Events\Bridges\Application\Event\RequestEvent given, called in ...\vendor\symfony\event-dispatcher\EventDispatcher.php on line 212`.

Okay, so obviously I don't need this. I notice you require `contributte/event-dispatcher-extra` so I look into the package to notice there is `Contributte\Events\Extra\DI\EventApplicationBridgeExtension` so I try to use it. Now I get: `Too few arguments to function Contributte\Events\Extra\Event\Application\PresenterStartupEvent::__construct(), 0 passed in ...temp\cache\Nette.Configurator\Container_689ab32e47.php on line 733 and exactly 1 expected`.

Am I doin't something wrong? Are instructions obsolete? Thanks for any help.

**Comment by josefsabl** [comment]
Just a note, commenting out [this](https://github.com/contributte/event-dispatcher-extra/blob/507568caeaa4c3491f94aceac68d1e885320d7e1/src/DI/EventApplicationBridgeExtension.php#L63) statement "fixed" the stuff.

**Comment by enumag** [comment]
Which version of arachne/entity-loader are you using?

**Comment by enumag** [comment]
There was indeed an error in the documentation. Fixed [here](https://github.com/Arachne/EntityLoader/commit/280bbe7cb1c30c40e019d5f440215cb840e6bc73).

Don't use `contributte/event-application-bridge`, it's obsolete. `contributte/event-dispatcher-extra` should be used instead. EntityLoader v0.13 should support this.

**Comment by josefsabl** [comment]
Latest (v0.13.0). I believe it's a bug in Contributte I am trying to fix [here](https://github.com/josefsabl/event-dispatcher-extra/commit/625c807df28e3e2951c04aa543679b06152ec668).

**Comment by josefsabl** [comment]
Sure, I found that out. That's what I wrote in the original question. But there's another problem. I got that fixed myself but am not sure if it is correct solution.

PS: Thanks for Arachne/Security. It's fantastic ;-)

**Comment by josefsabl** [comment]
I don't know... Look at [this](https://github.com/contributte/event-dispatcher-extra/blob/df8a23c7703f4f147e481ad15f817701974da8da/src/DI/EventApplicationBridgeExtension.php#L63)

This code can't work can it? The nested closure doesn't get paramters. I believe it is copy paste error. My pull request version works for me.

**Comment by josefsabl** [comment]
Sure, but I already installed my version. I will try to reproduce it :)

**Comment by mabar** [comment]
Closing for now, you are right. It's Contributte problem

**Comment by josefsabl** [comment]
```PHP
//Before
$service->onPresenter[] = function ($application, $presenter) {
	if (!property_exists($presenter, "onStartup")) {
		return;
	}
	$presenter->onStartup[] = function () {
		$this->getService('contributte.eventDispatcher.dispatcher')->dispatch(
			'nette.application.presenter.startup',
			new Contributte\Events\Extra\Event\Application\PresenterStartupEvent(
				...func_get_args()
			)
		)
		;
	};
};

//After
$service->onPresenter[] = function ($application, $presenter) {
	if (!property_exists($presenter, "onStartup")) {
		return;
	}
	$presenter->onStartup[] = function () use ($presenter) {
		$this->getService('contributte.eventDispatcher.dispatcher')->dispatch(
			'nette.application.presenter.startup',
			new Contributte\Events\Extra\Event\Application\PresenterStartupEvent(
				$presenter
			)
		)
		;
	};
};

**Comment by enumag** [comment]
@josefsabl Yeah this looks like the real problem. @mabar should be able to take care of it in Contributte. :-)

Thanks for reporting. Any feedback to Arachne/EntityLoader, Arachne/Security and the other packages is appreciated. Do you know about Arachne/Verifier too?

**Comment by josefsabl** [comment]
Yea, I implemented it yesterday. Now EntityLoader works so I will stitch the two together. The whole stuff is very cool. I stumbled upon it when researching possibility to have two separate identities logged in at the same time and, boy, was I happy :-) So firewall was the first stuff I implemented. ACL came second with which I was happy to replaced my solution for owned resources.

Feel free to delete this comment as it clearly doesn't belong here, I just wanted to share. And you asked ^_^

**Comment by josefsabl** [comment]
See [this](https://github.com/contributte/event-dispatcher-extra/pull/16) please. Not sure whether it is a problem in Contributte or Arachne but it indeed is a problem :-) I think it could be fixed quite easily here.

Nette itself invokes the onStartup with $this (presenter) as parameter so trait could do it as well.
